// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaa9Oapv2yKWvx68Czzv4BmESxY_DqDkY',
    appId: '1:542589366256:web:36ecf51df429dcc5037735',
    messagingSenderId: '542589366256',
    projectId: 'srijan6',
    authDomain: 'srijan6.firebaseapp.com',
    databaseURL: 'https://srijan6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srijan6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4XGkK0G4TUyomn_mkylriONhnGmsRPUQ',
    appId: '1:542589366256:android:731d9c71769e9b4f037735',
    messagingSenderId: '542589366256',
    projectId: 'srijan6',
    databaseURL: 'https://srijan6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srijan6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPGXc6baBilPOlLMiQr6sL-1yRXU6Sfw8',
    appId: '1:542589366256:ios:6885e298465b585b037735',
    messagingSenderId: '542589366256',
    projectId: 'srijan6',
    databaseURL: 'https://srijan6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srijan6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPGXc6baBilPOlLMiQr6sL-1yRXU6Sfw8',
    appId: '1:542589366256:ios:6885e298465b585b037735',
    messagingSenderId: '542589366256',
    projectId: 'srijan6',
    databaseURL: 'https://srijan6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srijan6.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaa9Oapv2yKWvx68Czzv4BmESxY_DqDkY',
    appId: '1:542589366256:web:13bbd10ca15cccf8037735',
    messagingSenderId: '542589366256',
    projectId: 'srijan6',
    authDomain: 'srijan6.firebaseapp.com',
    databaseURL: 'https://srijan6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'srijan6.appspot.com',
  );

}